# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
on:
  workflow_call:
    inputs:
      ref:
        description: "The git ref to checkout"
        required: false
        type: string
        default: ""
      working-directory:
        description: "Working directory for the workflow"
        required: false
        type: string
        # default: "${{ vars.WORKING_DIR || '.' }}"
      include-slow-tests:
        description: "Whether to include slow tests"
        required: false
        type: boolean
        default: true
  push:
    branches-ignore:
      - "queue-main-*"
      - "queue-dev-*"
  pull_request:
jobs:
  build:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Build
      run: go build -v ./...
  test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: "${{ inputs.working-directory || '.'}}/go.mod"
          cache: true

      - name: Cache Go 1.24.1
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-go1.24.1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go1.24.1-

      - name: Install tools
        run: |
          go install golang.org/x/tools/gopls@latest
          go install gotest.tools/gotestsum@latest
          go install mvdan.cc/gofumpt@latest
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Go generate
        working-directory: ${{ inputs.working-directory || '.'}}
        run: |
          go generate ./...
          # if go generate created a diff
          if ! git diff --exit-code; then
            echo "go generate created a diff"
            git diff
            exit 1
          fi

      - name: Run tests
        working-directory: ${{ inputs.working-directory || '.'}}
        run: |
          if [ "${{ inputs.include-slow-tests }}" = "false" ]; then
            echo "Running tests without slow tests (short mode, no race re-run)"
            GOEXPERIMENT=synctest gotestsum --format testname --jsonfile test-results.json -- -short ./...
          else
            echo "Running full test suite including slow tests"
            GOEXPERIMENT=synctest gotestsum --format testname --jsonfile test-results.json -- ./...
            GOEXPERIMENT=synctest gotestsum --format testname --jsonfile test-results-race.json -- -race ./...
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_id }}
          path: |
            ${{ inputs.working-directory || '.'}}/test-results.json
            ${{ inputs.working-directory || '.'}}/test-results-race.json
          retention-days: 30
