# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Smoke Test
on:
  workflow_call:
    inputs:
      ref:
        description: "The git ref to checkout"
        required: false
        type: string
        default: ""
      working-directory:
        description: "Working directory for the workflow"
        required: false
        type: string
        # default: "${{ vars.WORKING_DIR || '.' }}"
  push:
    branches-ignore:
      - "queue-main-*"
      - "queue-dev-*"
  pull_request:
jobs:
  install:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Install
      run: go install github.com/banksean/apple-container/cmd/sand
  test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: "${{ inputs.working-directory || '.'}}/go.mod"
          cache: true

      - name: Cache Go 1.24.1
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-go1.24.1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go1.24.1-

      - name: sand version
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand version

      - name: sand doc
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand doc
